# Generated by Django 6.0.7 on 2026-07-28 17:14

import django.db.models.deletion
import netbox.models.deletion
import taggit.managers
import utilities.json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('extras', '0140_imageattachment_image_size'),
        ('users', '0016_default_ordering_indexes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('service_type', models.CharField(default='application', max_length=30)),
                ('status', models.CharField(default='active', max_length=30)),
                ('health_status', models.CharField(default='unknown', max_length=30)),
                ('tier_level', models.CharField(default='tier-3', max_length=30)),
                ('sla_target', models.CharField(blank=True, max_length=20)),
                ('owner_contact', models.CharField(blank=True, max_length=200)),
                ('escalation_contact', models.CharField(blank=True, max_length=200)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itsm_services', to='users.owner')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'service',
                'verbose_name_plural': 'services',
                'ordering': ('name',),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('relationship_type', models.CharField(default='hard-dependency', max_length=30)),
                ('criticality', models.CharField(default='important', max_length=30)),
                ('depends_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='netbox_itsm.service')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbound_dependencies', to='netbox_itsm.service')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'service dependency',
                'verbose_name_plural': 'service dependencies',
                'ordering': ('service', 'depends_on'),
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='service',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='+', through='netbox_itsm.ServiceDependency', to='netbox_itsm.service'),
        ),
        migrations.CreateModel(
            name='ServiceAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, null=True)),
                ('custom_field_data', models.JSONField(blank=True, default=dict, encoder=utilities.json.CustomFieldJSONEncoder)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('comments', models.TextField(blank=True)),
                ('asset_id', models.PositiveBigIntegerField()),
                ('link_type', models.CharField(default='runs-on', max_length=30)),
                ('asset_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='users.owner')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='netbox_itsm.service')),
                ('tags', taggit.managers.TaggableManager(through='extras.TaggedItem', to='extras.Tag')),
            ],
            options={
                'verbose_name': 'service asset',
                'verbose_name_plural': 'service assets',
                'ordering': ('service', 'asset_type', 'asset_id'),
                'indexes': [models.Index(fields=['asset_type', 'asset_id'], name='netbox_itsm_asset_t_17b0a5_idx')],
                'constraints': [models.UniqueConstraint(fields=('service', 'asset_type', 'asset_id', 'link_type'), name='netbox_itsm_serviceasset_unique_service_asset_link')],
            },
            bases=(netbox.models.deletion.DeleteMixin, models.Model),
        ),
        migrations.AddConstraint(
            model_name='servicedependency',
            constraint=models.UniqueConstraint(fields=('service', 'depends_on'), name='netbox_itsm_servicedependency_unique_service_depends_on'),
        ),
    ]
